name: pull-request
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch: 
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Validate Packer Template
        uses: hashicorp/packer-github-action@main
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json
        env:
            PACKER_LOG: 1 # enable debug log for packer
